# Generated by Django 4.1.5 on 2023-02-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, verbose_name="email address"
            ),
        ),
    ]
