# Generated by Django 4.1.5 on 2023-01-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserved',
            old_name='product_id',
            new_name='product',
        ),
    ]
