# Generated by Django 4.1.5 on 2023-01-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0002_rename_product_id_reserved_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='shopy.product'),
        ),
    ]
