# Generated by Django 4.1.5 on 2023-01-24 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopy", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=6,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
