# Generated by Django 4.1.5 on 2023-01-24 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopy", "0004_alter_account_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserved",
            name="product_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shopy.product",
            ),
        ),
        migrations.AlterField(
            model_name="reserved",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
