version: '3.9'
services:

  web:
    build: 
      context: .
    command: >
        bash -c "python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Shopy:/Shopy
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=noname
      - POSTGRES_DB=nerdy
volumes:
  postgres_data:
